# Generated by Django 5.0.3 on 2024-03-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoAPI", "0002_todo_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
